import { test, expect } from '@playwright/test';
// Set values in .env: TEST_WALLET_SEED_PHRASE, TEST_WALLET_PASSWORD

test('deploy with the SmartPy online IDE', async ({ page }) => {
  await page.goto('https://wallet.kukai.app/');
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.getByText('Import Wallet').first().click();
  await page.getByText('Seed Words').click();
  await page.getByRole('textbox', { name: 'Seed Words (required)' }).click();
  await page.getByRole('textbox', { name: 'Seed Words (required)' }).fill(process.env.TEST_WALLET_SEED_PHRASE);
  await page.getByRole('button', { name: 'Import' }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill(process.env.TEST_WALLET_PASSWORD);
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill(process.env.TEST_WALLET_PASSWORD);
  await page.getByRole('button', { name: 'Next' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download' }).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: 'Open Wallet' }).click();
  await page1.goto('https://smartpy.tezos.com/');
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('link', { name: 'IDE', exact: true }).click();
  const page2 = await page2Promise;
  await page2.getByRole('tab', { name: 'Templates' }).click();
  await page2.getByRole('button', { name: 'Simple examples' }).click();
  await page2.getByRole('button', { name: 'Calculator A simple' }).click();
  await page2.getByRole('button', { name: 'Import' }).click();
  await page2.getByRole('button', { name: 'Close' }).click();
  await page2.getByRole('button', { name: 'run-code' }).click();
  await page2.getByRole('button', { name: 'Deploy contract' }).click();
  const page3Promise = page2.waitForEvent('popup');
  await page2.getByRole('button', { name: 'Continue' }).click();
  const page3 = await page3Promise;
  await page3.getByText('Mainnet').click();
  await page3.getByRole('option', { name: 'Ghostnet' }).click();
  await page3.getByRole('button', { name: 'Select Account' }).click();
  await page3.getByRole('tab', { name: 'Beacon' }).click();
  await page3.getByRole('img', { name: 'Kukai logo' }).click();
  const page4Promise = page3.waitForEvent('popup');
  await page3.getByRole('button', { name: 'Use Browser' }).click();
  const page4 = await page4Promise;
  await page4.getByRole('button', { name: 'Accept' }).click();
  await page4.getByText('Import Wallet').first().click();
  await page4.getByText('Seed Words').click();
  await page4.getByRole('textbox', { name: 'Seed Words (required)' }).click();
  await page4.getByRole('textbox', { name: 'Seed Words (required)' }).fill(process.env.TEST_WALLET_SEED_PHRASE);
  await page4.getByRole('button', { name: 'Import' }).click();
  await page4.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page4.getByRole('textbox', { name: 'Password', exact: true }).fill(process.env.TEST_WALLET_PASSWORD);
  await page4.getByRole('textbox', { name: 'Password', exact: true }).press('Tab');
  await page4.getByRole('textbox', { name: 'Confirm Password' }).fill(process.env.TEST_WALLET_PASSWORD);
  await page4.getByRole('button', { name: 'Next' }).click();
  const download1Promise = page4.waitForEvent('download');
  await page4.getByRole('button', { name: 'Download' }).click();
  const download1 = await download1Promise;
  await page4.getByRole('button', { name: 'Open Wallet' }).click();
  await page4.getByRole('button', { name: 'Connect' }).click();
  await page4.getByRole('button', { name: 'Connect' }).click();
  await page4.getByRole('button', { name: 'Connect' }).click();
  await page3.getByRole('button', { name: 'Validate' }).click();
  await page3.getByRole('button', { name: 'copy' }).click();
  await page3.getByRole('button', { name: 'Deploy Contract' }).click();
  await page3.getByRole('button', { name: 'Accept' }).click();
  await page3.getByRole('button', { name: 'Deploy Contract' }).click();
  await page3.getByRole('button', { name: 'Accept' }).click();
  await page3.locator('div').filter({ hasText: /^Error$/ }).nth(1).click();
});